#!/usr/bin/env bash

# Load utils
source ${DOTFILES_INSTALLER}/utils

###############################################################################
# BREW
###############################################################################

print_question 'Install Brew and all apps...\n'

# Install/Update Homebrew
if cmd_exists 'brew'; then
  print_success 'Updating Brew.\n'
  brew update
else
  print_success 'Installing Brew.\n'
  /usr/bin/ruby -e \
    "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Copy dotfiles Brewfile to Home
ln -s ${DOTFILES_FILES}/Brewfile ~/.Brewfile

# Install from local Brewfile
ask_for_confirmation 'Would you like to install all apps from Brewfile?'

if answer_is_yes; then
  brew bundle --global
  print_success 'Brew and all apps installed.\n'
else
  print_success 'Only Brew installed.\n'
fi
