#!/usr/bin/env bash
source ${DOTFILES_INSTALLER}/utils

print_question 'Starting Git Configuration...\n'

# Create symbolic link to default files
ln -s ${DOTFILES_FILES_CONFIGS}/.gitconfig ~/.gitconfig
ln -s ${DOTFILES_FILES_CONFIGS}/.gitignore ~/.gitignore

# Set Git user and email
git config --global user.name "$GIT_NAME"
git config --global user.email "$GIT_EMAIL"
git config --global github.user "$GITHUB_USER"

# Default .gitignore
# git config --global core.excludesfile ~/.gitignore

# Default editor
# git config --global core.editor subl --wait

# Signing commits using GPG
# git config --global commit.gpgsign true

print_success 'Git Configuration done!\n'
