#!/usr/bin/env bash
print_question 'Ruby configurations...\n'

# Create symbolic link to default files
ln -s ${DOTFILES_FILES_CONFIGS}/.gemrc ~/.gemrc
ln -s ${DOTFILES_FILES_CONFIGS}/.irbrc ~/.irbrc
ln -s ${DOTFILES_FILES_CONFIGS}/.pryrc ~/.pryrc

# Create default file to irb history
touch ~/.irb-history

# RBenv installs
ask_for_confirmation 'Would you like to install ruby versions [2.3/2.4]?'

if answer_is_yes; then
  print_success 'Installing ruby versions.\n'
  rbenv install 2.3.0
  rbenv install 2.4.0
  rbenv global 2.3.0
  print_success 'Ruby installed with 2.30 default.\n'
else
  print_success 'Skipping ruby installation.\n'
fi
