#!/usr/bin/env bash
source ${DOTFILES_INSTALLER}/utils

print_question 'Installing Ruby versions and configurations...\n'

# Create symbolic link to default files
ln -s ${DOTFILES_FILES_CONFIGS}/.gemrc ~/.gemrc
ln -s ${DOTFILES_FILES_CONFIGS}/.irbrc ~/.irbrc

# Create default file to irb history
touch ~/.irb-history

# RBenv installs
rbenv install 2.3.0
rbenv install 2.4.0

# RBenv default version
rbenv global 2.3.0

print_success 'Ruby installed.\n'
