#!/usr/bin/env bash

# Create symbolic link to default files
ln -s ${DOTFILES_FILES}/.gitconfig ~/.gitconfig
ln -s ${DOTFILES_FILES}/.gitignore ~/.gitignore

ln -s ${DOTFILES_FILES}/.gemrc ~/.gemrc
ln -s ${DOTFILES_FILES}/.inputrc ~/.inputrc

# Create default files
touch ~/.bash_history
touch ~/.irb-history
