#!/usr/bin/env bash

git config --global user.name "$GIT_NAME"
git config --global user.email "$GIT_EMAIL"
git config --global github.user "$GITHUB_USER"

git config --global core.excludesfile ~/.gitignore
git config --global commit.gpgsign true
