#!/usr/bin/env bash
source ${DOTFILES_INSTALLER}/utils

# Check and install any remaining software updates.
sudo softwareupdate --install --all

# Install the Xcode Command Line Tools.
xcode-select --install
sudo xcodebuild -license accept
