#!/usr/bin/env bash
source ${DOTFILES_INSTALLER}/utils

print_success 'OS X Softwares updating and installing Xcode Command Line tools...'

# Check and install any remaining software updates.
sudo softwareupdate --install --all

# Install the Xcode Command Line Tools.
xcode-select --install
sudo xcodebuild -license accept

print_success 'OS X Softwares installed and updated.'
