#!/usr/bin/env bash
source ${DOTFILES_INSTALLER}/utils

print_question 'Changing to ZSH and installing Oh-My-Zsh with extras...\n'

# Change my shell to zsh
chsh -s /bin/zsh

# Install OH MY ZSH
cd ~
curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh &> /dev/null

# Install default theme
mkdir -p ~/.oh-my-zsh/custom/themes
ln -s ${DOTFILES_FILES}/diegorv.zsh-theme ~/.oh-my-zsh/custom/themes/diegorv.zsh-theme

print_success 'Oh-My-Zsh installed.\n'
