#!/usr/bin/env bash

# Change my shell to zsh
chsh -s $(type -ap zsh | grep $(brew --prefix))

# Install OH MY ZSH
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

# Copy my ZSH config
ln -s ${DOTFILES_FILES}/.zshrc ~/.zshrc
