#!/usr/bin/env bash

# From https://raw.githubusercontent.com/alrra/dotfiles/master/src/os/utils.sh

answer_is_yes() {
  [[ "$REPLY" =~ ^[Yy]$ ]] \
    && return 0 \
    || return 1
}

ask_for_confirmation() {
  print_question "$1 (y/n) "
  read -n 1
  printf "\n"
}

cmd_exists() {
  command -v "$1" &> /dev/null
  return $?
}

ask_for_sudo() {
  # Ask for the administrator password upfront.

  sudo -v &> /dev/null

  # Update existing `sudo` time stamp
  # until this script has finished.
  #
  # https://gist.github.com/cowboy/3118588

  while true; do
    sudo -n true
    sleep 60
    kill -0 "$$" || exit
  done &> /dev/null &
}

print_error() {
  print_in_red "  [✖] $1 $2\n"
}

print_in_green() {
  printf "\e[0;32m$1\e[0m"
}

print_in_purple() {
  printf "\e[0;35m$1\e[0m"
}

print_in_red() {
  printf "\e[0;31m$1\e[0m"
}

print_in_yellow() {
  printf "\e[0;33m$1\e[0m"
}

print_question() {
  print_in_yellow "  [?] $1"
}

print_success() {
  print_in_green "  [✔] $1\n"
}
